# ZanSoc Worker Node Configuration

# Master node connection settings
master_ip: "100.101.84.71"  # Tailscale IP
master_port: 6379
redis_password: "zansoc_secure_password_change_me"  # Must match master's password

# Network settings for the worker (e.g., logging)
log_to_driver: True
logging_level: INFO
log_dir: "logs"

# Connection retry settings
connection_retries: 5
connection_timeout_s: 30